name: Auto PR and Tag on Main Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  auto-pr-and-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get PR branch name
      id: branch
      run: |
        BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
        echo "name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "PR branch name: $BRANCH_NAME"
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Fetch all branches
      run: |
        git fetch origin
        git fetch origin ${{ steps.branch.outputs.name }}:${{ steps.branch.outputs.name }} || true
        git fetch origin develop:develop
    
    - name: Create PR from branch to develop
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check if the PR branch still exists
        if git show-ref --verify --quiet refs/heads/${{ steps.branch.outputs.name }}; then
          # Check if a PR already exists
          EXISTING_PR=$(gh pr list --base develop --head ${{ steps.branch.outputs.name }} --state open --json number --jq '.[0].number' || echo "")
          
          if [ -z "$EXISTING_PR" ]; then
            # Create new PR
            gh pr create \
              --base develop \
              --head ${{ steps.branch.outputs.name }} \
              --title "Develop: ${{ steps.branch.outputs.name }}" \
              --body "## Summary
Automatically created PR to merge changes from \`${{ steps.branch.outputs.name }}\` into \`develop\` branch.

This PR was created because the branch was merged into \`main\`.

## Related PR
- Original PR: #${{ github.event.pull_request.number }}
- Title: ${{ github.event.pull_request.title }}

---
*This PR was automatically generated by GitHub Actions*" || echo "Failed to create PR (branch might not have new commits for develop)"
          else
            echo "PR already exists: #$EXISTING_PR"
          fi
        else
          echo "Branch ${{ steps.branch.outputs.name }} no longer exists, skipping PR creation"
        fi
    
    - name: Create tag for the branch
      run: |
        # Create tag from the merge commit
        TAG_NAME="${{ steps.branch.outputs.name }}"
        MERGE_COMMIT="${{ github.event.pull_request.merge_commit_sha }}"
        
        # Check if tag already exists
        if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
          echo "Tag $TAG_NAME already exists, skipping tag creation"
        else
          git tag -a "$TAG_NAME" "$MERGE_COMMIT" -m "Tag for PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          git push origin "$TAG_NAME"
          echo "Created and pushed tag: $TAG_NAME"
        fi