name: Lab Branch Ruff Check

on:
  push:
    branches: [ lab ]

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full git history for changed files detection
    
    - name: Get changed Python files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          **/*.py
        separator: ' '
    
    - name: Set up Python
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install ruff
      if: steps.changed-files.outputs.any_changed == 'true'
      run: pip install ruff
    
    - name: Make script executable
      if: steps.changed-files.outputs.any_changed == 'true'
      run: chmod +x .github/scripts/ruff-diff-check.py
    
    - name: Run ruff check on changed lines only
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        python .github/scripts/ruff-diff-check.py ${{ steps.changed-files.outputs.all_changed_files }}
