name: Lab Branch Ruff Check

on:
  push:
    branches: [ lab ]

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run reviewdog with ruff
      uses: benny123tw/action-ruff@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        filter_mode: diff_context
        fail_level: none
        level: info
        tool_name: ruff