name: Lab Branch Ruff Check

on:
  push:
    branches: [ lab ]

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full git history for reviewdog diff context
    
    - name: Run reviewdog with ruff
      uses: jiayun/action-ruff@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        filter_mode: file
        fail_level: error
        level: error
        tool_name: ruff
        changed_files: true